name = "Template Modpack"
author = "yourname"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94b120c70ca5a5387dcc6789f39dd1399f8976224de746cf0d26f8a819338c79"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
